version: '3.9'

services:
  vite-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8089
